#!/bin/bash

exec=./example
K=1.5
for mode in 0 1; do
    results=results-mode-$mode/
    mkdir -p $results
    for A in 1 4 20 84 31; do
        $exec $mode $K $A
        mv test.dat $results/$A.dat
    done
done

